"""
FINAL ERROR-FREE DATA EXPLORATION SCRIPT
----------------------------------------

Runs on any Windows system without pandas buffer errors.
Generates:
 - Console summary
 - Figures in outputs/figures/
 - Markdown report in outputs/exploration_report.md
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")        # Prevent backend errors
import matplotlib.pyplot as plt
from pathlib import Path

# -----------------------------------------
# PATH SETUP
# -----------------------------------------
BASE = Path(__file__).resolve().parents[1]
DATA_PATH = BASE / "data" / "sample_sales.csv"
OUTPUT_DIR = BASE / "outputs"
FIG_DIR = OUTPUT_DIR / "figures"
REPORT_PATH = OUTPUT_DIR / "exploration_report.md"

FIG_DIR.mkdir(parents=True, exist_ok=True)


# -----------------------------------------
# LOAD CSV SAFELY
# -----------------------------------------
def load_data():
    if not DATA_PATH.exists():
        print("ERROR: sample_sales.csv not found in /data folder.")
        exit()

    try:
        df = pd.read_csv(DATA_PATH, parse_dates=["order_date"])
    except:
        df = pd.read_csv(DATA_PATH)
        if "order_date" in df.columns:
            df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

    return df


# -----------------------------------------
# MAIN FUNCTION
# -----------------------------------------
def main():

    df = load_data()

    print("\n=== FIRST 10 ROWS ===")
    print(df.head(10))

    print("\n=== INFO ===")
    df.info()             # No buffer → No error

    print("\n=== DATA TYPES ===")
    print(df.dtypes)

    print("\n=== MISSING VALUES (BEFORE) ===")
    print(df.isna().sum())


    # -----------------------------------------
    # CLEANING
    # -----------------------------------------
    df = df.copy()

    if "discount_pct" in df.columns:
        df["discount_pct"] = pd.to_numeric(df["discount_pct"], errors="coerce").fillna(0)

    if "customer_id" in df.columns:
        df["customer_id"] = df["customer_id"].fillna("Unknown")

    df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")
    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

    df = df.dropna(subset=["unit_price", "quantity"])


    print("\n=== MISSING VALUES (AFTER) ===")
    print(df.isna().sum())


    # -----------------------------------------
    # FEATURE ENGINEERING
    # -----------------------------------------
    df["total_price"] = df["unit_price"] * df["quantity"]
    df["final_price"] = df["total_price"] * (1 - df["discount_pct"] / 100)

    if "order_date" in df.columns:
        df["order_month"] = df["order_date"].dt.to_period("M")

    print("\n=== HEAD WITH NEW FEATURES ===")
    print(df.head(10))


    # -----------------------------------------
    # PLOTS
    # -----------------------------------------
    print("\n=== GENERATING PLOTS ===")

    # 1) Histogram of final price
    plt.figure()
    plt.hist(df["final_price"], bins=30)
    plt.title("Distribution of Final Price")
    plt.xlabel("Final Price")
    plt.ylabel("Count")
    plt.savefig(FIG_DIR / "hist_final_price.png")
    plt.close()

    # 2) Sales by product
    plt.figure()
    df.groupby("product")["final_price"].sum().plot(kind="bar")
    plt.title("Sales by Product")
    plt.ylabel("Total Sales")
    plt.savefig(FIG_DIR / "sales_by_product.png")
    plt.close()

    # 3) Scatter: quantity vs final price
    plt.figure()
    plt.scatter(df["quantity"], df["final_price"])
    plt.title("Quantity vs Final Price")
    plt.xlabel("Quantity")
    plt.ylabel("Final Price")
    plt.savefig(FIG_DIR / "scatter_quantity_finalprice.png")
    plt.close()

    print("Plots saved in outputs/figures/")


    # -----------------------------------------
    # REPORT
    # -----------------------------------------
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("# Data Exploration Report\n\n")
        f.write("Generated by data_exploration.py\n\n")
        f.write("## Basic Info\n")
        f.write(f"- Total rows: {len(df)}\n")
        f.write("- Columns:\n")
        for col in df.columns:
            f.write(f"  - {col}\n")

        f.write("\n## Missing Values After Cleaning\n")
        f.write(df.isna().sum().to_string())

        f.write("\n\n## Numeric Summary\n")
        f.write(df.describe().to_string())

        f.write("\n\n## Figures Saved\n")
        for img in FIG_DIR.iterdir():
            f.write(f"- {img.name}\n")

    print("\n=== REPORT GENERATED ===")
    print("See: outputs/exploration_report.md")

    print("\n=== DONE ===")


# -----------------------------------------
# RUN PROGRAM
# -----------------------------------------
if __name__ == "__main__":
    main()
